### ISSUE TITLE
What an amazing example of how to ensure study reproducibility!

### ISSUE THREAD

**Issue by gabrielmongefranco** [IrinaStatsLab/GlucoBench#13]
Hi Irina!

This issue isn't really an issue - I just wanted to express my gratitude for your amazing documentation on this project! Your README file is a really, really good example of how to share data and ensure reproducibility of scientific studies. I love the how-to section! :)

Gabriel Mongefranco
Mobile Data Architect
[Eisenberg Family Depression Center](https://www.depressioncenter.org/), University of Michigan

**Comment by irinagain** [comment]
Thank you for the praise, but Renat is really the one beyond the excellent documentation and implementation.
