### ISSUE TITLE
dependency management has issues

### ISSUE THREAD

**Issue by Livia-Zaharia** [IrinaStatsLab/GlucoBench#5]
I discovered that you made your environment.yaml not in proper way: you hardcoded specific versions (like  gst-plugins-base=1.14.0=h8213a91_2) which causes incompartibilities for people creating environments from other operating systems. Feels like you had someting like pip freeze instead of writing requirements by hand with lower and upper bounds. This makes your code incompartible between platforms.
I also checked requirements.txt and there you also have problems. In your code you are using tensorboard and some other dependencies which are not mentioned in requirements.

**Comment by antonkulaga** [comment]
I agree, the way environment yaml is written is useless. I think just having upper and lower bounds of dependencies without specifying transient dependencies would be much better.

**Comment by mrsergazinov** [comment]
Thanks for the fix @antonkulaga ! I just merged and checked, the deprecation warnings are solved.
