### ISSUE TITLE
 DataFrame.fillna is deprecated

### ISSUE THREAD

**Issue by Livia-Zaharia** [IrinaStatsLab/GlucoBench#6]
You are using a lot of deprecated methods that bloats the console output. For example  DataFrame.fillna

**Comment by antonkulaga** [comment]
I suggested a pull request to fix this https://github.com/IrinaStatsLab/GlucoBench/pull/7

**Comment by antonkulaga** [comment]
Look like my PR was merged. @Livia-Zaharia do you think you can close this?
