### ISSUE TITLE
can we contribute more data?

### ISSUE THREAD

**Issue by antonkulaga** [IrinaStatsLab/GlucoBench#8]
I see that some datasets are really small. If I talk with my friends we can easily get 5-10 samples of years long Dexcom and Libre for diabetic and wildtype people. Are you open to including such dataset?

**Comment by mrsergazinov** [comment]
@antonkulaga This is interesting, and we definitely welcome community contributions! But we need to be careful regarding the data privacy, consent to share, licensing, etc. 

@irinagain What do you think?

**Comment by antonkulaga** [comment]
We can create the huggingface dataset with permisive license and your code might just download it to run a benchmark, so it will not be part of your repo. What do you think about it?

**Comment by mrsergazinov** [comment]
Sounds like a plan! Let us know when you publish the dataset. We could take a look and incorporate it into the benchmark.
@irinagain

**Comment by irinagain** [comment]
@antonkulaga @mrsergazinov Sorry for the delay, I think it would be great to add more datasets, we have some more at awesome-CGM repo (https://github.com/irinagain/Awesome-CGM) but didn't have the bandwidth. We definitely welcome community efforts on adding to and expanding the repository
